module.exports = {
  extends: [
    'stylelint-config-standard-scss',
    'stylelint-config-recess-order', // Property ordering
  ],
  plugins: ['stylelint-scss', 'stylelint-order'],
  rules: {
    // Allow both short and long hex colors (more flexible)
    'color-hex-length': null,

    // Spacing and formatting rules
    'rule-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignore: ['after-comment'],
      },
    ],
    'at-rule-empty-line-before': [
      'always',
      {
        except: ['first-nested', 'blockless-after-blockless'],
        ignore: ['after-comment'],
      },
    ],
    'comment-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignore: ['stylelint-commands'],
      },
    ],

    // SCSS specific overrides
    'scss/at-rule-no-unknown': null,
    'scss/dollar-variable-pattern': null, // Allow any variable naming
    'scss/double-slash-comment-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignore: ['between-comments', 'stylelint-commands'],
      },
    ],

    // CSS quality enforcement
    'no-descending-specificity': true,
    'no-duplicate-selectors': true,

    // CSS unit best practices - Promote rem over px for accessibility
    'unit-disallowed-list': [
      ['px'],
      {
        ignoreProperties: {
          px: [
            'border-width',
            'border',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'outline-width',
            'outline',
            'box-shadow',
            '/^border.*radius$/',
          ],
        },
        message: 'Use rem instead of px for better accessibility. Pixels are only allowed for borders and box-shadows.',
      },
    ],

    // Allow CSS modules naming
    'selector-class-pattern': null,
  },
  overrides: [
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
    {
      files: ['**/*.module.{css,scss}'],
      rules: {
        // More lenient rules for CSS modules
        'selector-pseudo-class-no-unknown': [
          true,
          {
            ignorePseudoClasses: ['export', 'import', 'global', 'local', 'external'],
          },
        ],
      },
    },
  ],
  ignoreFiles: [
    'node_modules/**/*',
    '.next/**/*',
    'src/styles/colors.module.scss', // Auto-generated by style-dictionary
    'src/styles/breakpoints.module.scss', // Auto-generated by style-dictionary
    'src/styles/*.ts', // TypeScript files generated by style-dictionary
  ],
};
